### PR TITLE
KeepLogs command to keep played songs history in chat

### PR DESCRIPTION
**Pull request by archv**
## Please describe the changes this PR makes and why it should be merged:

My friends and I wanted to keep the history of played songs in chat as 'Now playing' message keeps removed or updated.

So `/keeplogs` command is introduced: it prints the same embed as 'Now playing', but with 'Played track' header on every `handleTrackStart` event.

This feature is enabled by default.

I have also changed the following things in the code:
- `/247`, `/autoleave`, `/autopause`, `/autoqueue`, `/skip` and `/stop` now remove their message after time
- Replaced spaces with tabs in those commands' code
- Wrong `redEmbed` call in `/skip`
- Time in logs is now formatted properly
- Offsets in logs are now more clean

Please review.

## Status and versioning classification:

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added) (see `trackStartedEmbed`)

### CODE REVIEW

**Comment by archv** [comment]
A lot of changes in `package-lock.json` - bumbed package version and replaced spaces with tabs.

**Comment by Neko-Life** [comment]
Just tried it out, it clutter the control channel if ppl were to add song there. Imo better make a dedicated played track log channel like how control channel is having its own channel. @BioCla what do u think of this?

Btw new feature which doesn't include breaking changes should increment minor version. I will add some commit sometime later if @BioCla thinks this is a good feature to have

**Comment by Neko-Life** [comment]
also any opinion from others @DarrenOfficial @SudhanPlayz @LewdHuTao @sprucecellodev125 ? Imo just a nice to have feature

**Comment by LewdHuTao** [comment]
Looks good. But imo it is better to set keepPlayer logs to false for default. Some users just want a clean music-cmd channel

**Comment by BioCla** [comment]
Definitely keep it false as default. For the rest, sounds good 👍

**Comment by BioCla** [comment]
I just looked at the changes... there is way too much committed which is out of scope for the version. Please make a new PR with just the command and the relevant changes in the other sections of the code that delete the logs automatically.

**Pull request closed without merging**
